#!/usr/bin/env bash
# Configures a new ubuntu machine by installing
# Nginx where it should be listening on port 80
# Serve a page that would return a Hello World string

sudo apt-get update -y -qq 
sudo apt-get install nginx -y

# allowing nginx on firewall
sudo ufw allow 'Nginx HTTP'

# Creating new index
echo -e "Hello World!" | sudo tee /var/www/html/index.html
# Restarting nginx
sudo service nginx restart